[workspace]
members = ['sod', 'sod-actix-web', 'sod-bus', 'sod-crossbeam', 'sod-log', 'sod-mpsc', 'sod-tungstenite']
resolver = "2"
package.version = "0.4.2"
package.edition = "2021"

[workspace.dependencies]
sod = "0.4.2"
